#Created by webjeda - http://webjeda.com

title: Shivank Mishra #Keep it short
email: smishr25 AT illinois DOT edu


baseurl: /bheema

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
